# Sample .travis.yml for R projects.
#
# See README.md for instructions.

language: c
# To build on OSX, switch the previous line to
# language: objective-c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs
  
# Configuration options below this line are suggested options.
notifications:
  email:
    on_success: change
    on_failure: change

